import { Org } from "src/app/helpers/org.interface";

export const ORGS: Org[] = [
    {
        id: 0,
        guid: "00000000-0000-0000-0000-000000000000",
        regNumber: null,
        name: "ОАО \"СТАЛЬ\"",
        fullName: "ОТКРЫТОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО \"СТАЛЬ\"",
        inn: "7701516533",
        kpp: "775101001",
        organizationCountry: 0,
        organizationCountryName: null,
        organizationType: 0,
        organizationStatus: 0,
        contactPerson: null,
        isSMP: false,
        isCustomer: false,
        isSupplier: false,
        address: {
            id: 0,
            fullAddress: null,
            fullPostAddress: null,
            okato: null,
            regionRF: null,
            postIndex: null,
            kladrCodeRegionRF: "7700000000000",
            kladrNameRegionRF: "г Москва"
        },
        ogrn: "1037789060198",
        email: null
    },
    {
        id: 0,
        guid: "00000000-0000-0000-0000-000000000000",
        regNumber: null,
        name: "ПАО \"СТАЛЬ\"",
        fullName: "ПУБЛИЧНОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО \"СТАЛЬ\"",
        inn: "9403023511",
        kpp: "940301001",
        organizationCountry: 0,
        organizationCountryName: null,
        organizationType: 0,
        organizationStatus: 0,
        contactPerson: null,
        isSMP: false,
        isCustomer: false,
        isSupplier: false,
        address: {
            id: 0,
            fullAddress: null,
            fullPostAddress: null,
            okato: null,
            regionRF: null,
            postIndex: null,
            kladrCodeRegionRF: null,
            kladrNameRegionRF: null
        },
        ogrn: "1229400096254",
        email: null
    },
    {
        id: 0,
        guid: "00000000-0000-0000-0000-000000000000",
        regNumber: null,
        name: "АО \"УРАЛЬСКАЯ СТАЛЬ\"",
        fullName: "АКЦИОНЕРНОЕ ОБЩЕСТВО \"УРАЛЬСКАЯ СТАЛЬ\"",
        inn: "5607019523",
        kpp: "560701001",
        organizationCountry: 0,
        organizationCountryName: null,
        organizationType: 0,
        organizationStatus: 0,
        contactPerson: null,
        isSMP: false,
        isCustomer: false,
        isSupplier: false,
        address: {
            id: 0,
            fullAddress: null,
            fullPostAddress: null,
            okato: null,
            regionRF: null,
            postIndex: null,
            kladrCodeRegionRF: "5600000000000",
            kladrNameRegionRF: "Оренбургская обл"
        },
        ogrn: "1055607061498",
        email: null
    },
    {
        id: 0,
        guid: "00000000-0000-0000-0000-000000000000",
        regNumber: null,
        name: "АО \"ОМК СТАЛЬНОЙ ПУТЬ\"",
        fullName: "АКЦИОНЕРНОЕ ОБЩЕСТВО \"ОМК СТАЛЬНОЙ ПУТЬ\"",
        inn: "7708737500",
        kpp: "770501001",
        organizationCountry: 0,
        organizationCountryName: null,
        organizationType: 0,
        organizationStatus: 0,
        contactPerson: null,
        isSMP: false,
        isCustomer: false,
        isSupplier: false,
        address: {
            id: 0,
            fullAddress: null,
            fullPostAddress: null,
            okato: null,
            regionRF: null,
            postIndex: null,
            kladrCodeRegionRF: "7700000000000",
            kladrNameRegionRF: "г Москва"
        },
        ogrn: "1117746294115",
        email: null
    },
    {
        id: 0,
        guid: "00000000-0000-0000-0000-000000000000",
        regNumber: null,
        name: "АО \"СТАЛЬМОСТ\"",
        fullName: "АКЦИОНЕРНОЕ ОБЩЕСТВО \"СТАЛЬМОСТ\"",
        inn: "7224079673",
        kpp: "720301001",
        organizationCountry: 0,
        organizationCountryName: null,
        organizationType: 0,
        organizationStatus: 0,
        contactPerson: null,
        isSMP: false,
        isCustomer: false,
        isSupplier: false,
        address: {
            id: 0,
            fullAddress: null,
            fullPostAddress: null,
            okato: null,
            regionRF: null,
            postIndex: null,
            kladrCodeRegionRF: "7200000000000",
            kladrNameRegionRF: "Тюменская обл"
        },
        ogrn: "1187232026101",
        email: null
    },
    {
        id: 0,
        guid: "00000000-0000-0000-0000-000000000000",
        regNumber: null,
        name: "ООО \"СТАЛЬ\"",
        fullName: "ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ \"СТАЛЬ\"",
        inn: "7413029117",
        kpp: "741301001",
        organizationCountry: 0,
        organizationCountryName: null,
        organizationType: 0,
        organizationStatus: 0,
        contactPerson: null,
        isSMP: false,
        isCustomer: false,
        isSupplier: false,
        address: {
            id: 0,
            fullAddress: null,
            fullPostAddress: null,
            okato: null,
            regionRF: null,
            postIndex: null,
            kladrCodeRegionRF: "7400000000000",
            kladrNameRegionRF: "Челябинская обл"
        },
        ogrn: "1227400026589",
        email: null
    },
    {
        id: 0,
        guid: "00000000-0000-0000-0000-000000000000",
        regNumber: null,
        name: "ООО \"СТАЛЬ\"",
        fullName: "ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ \"СТАЛЬ\"",
        inn: "5903087234",
        kpp: "590301001",
        organizationCountry: 0,
        organizationCountryName: null,
        organizationType: 0,
        organizationStatus: 0,
        contactPerson: null,
        isSMP: false,
        isCustomer: false,
        isSupplier: false,
        address: {
            id: 0,
            fullAddress: null,
            fullPostAddress: null,
            okato: null,
            regionRF: null,
            postIndex: null,
            kladrCodeRegionRF: "5900000000000",
            kladrNameRegionRF: "Пермский край"
        },
        ogrn: "1085903002987",
        email: null
    },
    {
        id: 0,
        guid: "00000000-0000-0000-0000-000000000000",
        regNumber: null,
        name: "ООО \"СТАЛЬ\"",
        fullName: "ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ \"СТАЛЬ\"",
        inn: "7105520659",
        kpp: "710501001",
        organizationCountry: 0,
        organizationCountryName: null,
        organizationType: 0,
        organizationStatus: 0,
        contactPerson: null,
        isSMP: false,
        isCustomer: false,
        isSupplier: false,
        address: {
            id: 0,
            fullAddress: null,
            fullPostAddress: null,
            okato: null,
            regionRF: null,
            postIndex: null,
            kladrCodeRegionRF: "7100000000000",
            kladrNameRegionRF: "Тульская обл"
        },
        ogrn: "1147154003325",
        email: null
    },
    {
        id: 0,
        guid: "00000000-0000-0000-0000-000000000000",
        regNumber: null,
        name: "ООО \"СТАЛЬ\"",
        fullName: "ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ \"СТАЛЬ\"",
        inn: "9723136377",
        kpp: "772301001",
        organizationCountry: 0,
        organizationCountryName: null,
        organizationType: 0,
        organizationStatus: 0,
        contactPerson: null,
        isSMP: false,
        isCustomer: false,
        isSupplier: false,
        address: {
            id: 0,
            fullAddress: null,
            fullPostAddress: null,
            okato: null,
            regionRF: null,
            postIndex: null,
            kladrCodeRegionRF: "7700000000000",
            kladrNameRegionRF: "г Москва"
        },
        ogrn: "1227700036926",
        email: null
    },
    {
        id: 0,
        guid: "00000000-0000-0000-0000-000000000000",
        regNumber: null,
        name: "ООО \"СТАЛЬ\"",
        fullName: "ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ \"СТАЛЬ\"",
        inn: "7714490032",
        kpp: "771401001",
        organizationCountry: 0,
        organizationCountryName: null,
        organizationType: 0,
        organizationStatus: 0,
        contactPerson: null,
        isSMP: false,
        isCustomer: false,
        isSupplier: false,
        address: {
            id: 0,
            fullAddress: null,
            fullPostAddress: null,
            okato: null,
            regionRF: null,
            postIndex: null,
            kladrCodeRegionRF: "7700000000000",
            kladrNameRegionRF: "г Москва"
        },
        ogrn: "1227700485638",
        email: null
    }
]